travis:
  secure:
    BINSTAR_TOKEN: OE0vbOohuIDNOLjzCY13JWPS3isC7IDYlWp6o4/notMtjhPoB6YXh80amQ3SWyS9QAnx6v4QLdXzHhaKE1JdLxGmoYKdyDAeQiQHUDqMNsmphqFr862R1VYNwNIC/aaY1glLR0cIyuAtqlkKD/MAwNBKJl2jOv1zEGAT0WoQJmqQf4d3SoTbMUST5UoyOVPPPJqQgd4zhXVWZLqXOn2WD3HVNPMu0j754bFixu2pGfRS9jkMjJ+ajHB7Bc1SiAG9vEUOBy2wFqxOw0VegZyE92dEqicf35g+ETovQYJvc4vqs8X1Y3tDJOK2+t639E3Gmeus16vZEnYkXi4PEEu7gY6Fkx8vmbl3kOE+ilbllUiillcBn8jS9+6PiCK4Y7bAaapbi0HfB79AF2H0FVSeEzEaQD073WsTwqEMTehXZNQGtqSzuA8axxarjENnMh2SNUeKy+TD0wN24s2IQGWg24fPGL8bwvVxXp88J2hzSw8fr/5kQ2ADvwd+pnjJvbaWQ9AnuBmzYBzy+hYutL+Z9XaKm9Orm1O3QLw/VKkPxtYa6QIdg+OAGq2Vf6pGWnCUPUJDVjPmOI3yOtgWuFXIvrFkCoQuwc9oJOYHGOG0uP9tbCCgIVWQMP4IKO3tdoavCmvoaswifV99Rl38j2m68y9XX4m5e9t3kRGHdUdFohg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
